version: 2
jobs:
  build:
    working_directory: ~/socialbank
    docker:
      - image: circleci/node:8.4.0
      - image: mongo:3.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --ignore-optional --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.4.0
      - image: mongo:3.4
    steps:
      - checkout
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
