version: 2
jobs:
  build:
    working_directory: ~/socialbank
    docker:
      - image: circleci/node:8.4.0
      - image: mongo:3.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --ignore-optional --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi
