export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
export const SELECT_CURRENT_PROJECT = 'SELECT_CURRENT_PROJECT'
// Card Actions
//TEMPORARY: START
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'
export const RECEIVE_CARDS = 'RECEIVE_CARDS'
export const BLOCK_CARD = 'BLOCK_CARD'
export const UNBLOCK_CARD = 'UNBLOCK_CARD'
export const DESTROY_CARD = 'DESTROY_CARD'
export const UPDATE_CARD = 'UPDATE_CARD'
// TEMPORARY: END
