export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const CLOSE_PROJECT_SUCCESS = 'CLOSE_PROJECT_SUCCESS'
export const DEPOSIT_PROJECT_SUCCESS = 'DEPOSIT_PROJECT_SUCCESS'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
export const SELECT_CURRENT_PROJECT = 'SELECT_CURRENT_PROJECT'

export const RECEIVE_CARDS = 'RECEIVE_CARDS'
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'

export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS'
export const REGISTER_ACCOUNT_FAILURE = 'REGISTER_ACCOUNT_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const RECEIVE_ORGANIZATIONS = 'RECEIVE_ORGANIZATIONS'
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
