export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
export const SELECT_CURRENT_PROJECT = 'SELECT_CURRENT_PROJECT'

export const RECEIVE_CARDS = 'RECEIVE_CARDS'
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'

export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS'
export const REGISTER_ACCOUNT_FAILURE = 'REGISTER_ACCOUNT_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
