import React from 'react'

import Header from '../components/Header'
import MobileNavigation from '../components/MobileNavigation'
import Footer from '../components/Footer'

class About extends React.Component {
  render () {
    const styleText = {textAlign: 'justify'}

    return (
      <div className="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <Header />
        <MobileNavigation />
        <main className="mdl-layout__content">
          <div className="page-content">
            <div className="sb-form-content sb-page" style={styleText}>
              <h1 id="socialbanktermsofserviceprivacypolicy">SocialBank Terms of Service &amp; Privacy Policy</h1>

              <h2 id="termsofservice">Terms of Service</h2>

              <h3 id="introduction">Introduction</h3>

              <p>The services to which these terms of service relate are provided by SocialBank (we, us or our).</p>

              <p>These terms govern your access to and use of the services. If you want to download or use our applications (Apps), website <a href="www.socialbank.co">www.socialbank.co</a> or other services as operated and made available by us from time to time (Services) you have to agree to these terms and you acknowledge that these terms form a legally-binding contract between us and you. If you do not want to be bound by these terms, then you should not download or use the Apps, website or other services.</p>

              <p>We may change these terms from time to time by updating the Apps and by updating the copy of the terms that is on our <a href="/">website</a>.</p>

              <p>These terms were last updated on 2nd June 2017.</p>

              <h3 id="whatwedo">What we do</h3>

              <p>Our Apps have been designed to allow you to store and share your own recommendations or 'pearls of wisdom' (“Pearls”) and groups of Pearls ("Guides") either with other users of the Service and/or friends and to enable you to find and locate new Pearls and Guides both in your local area and worldwide.</p>

              <p>You may also choose to share Pearls or Guides to friends and to the wider public who do not use the Service by sharing a URL web link (generated by us) which can be copied into an email or other messaging service (whether instant or otherwise) of your choice.</p>

              <p>You can decide whether to make Pearls or Guides available to your friends who use the Service and also to the wider public. Any factual information (such as phone numbers, addresses, website URLs, photos and other similar information) relating to Pearls which you upload to the Service will automatically be publically available to other users of the Service. You can choose to make other elements of each Pearl public or private (such as comments or private notes) by setting your privacy settings for each Pearl or Guide before that Pearl or Guide is posted to the Service.</p>

              <h3 id="accesstotheapps">Access to the Apps</h3>

              <p>The Apps may only be downloaded, accessed and used on a device owned or controlled by you, running the relevant operating system for which the Apps were designed. Please ensure you have a compatible device which meets all the necessary technical specifications to enable you to download, access and use the Apps.</p>

              <p>We may, from time to time, restrict the download of our Apps from our website or limit access to certain features, functions or content of the Apps downloaded from any third party application store, to users who have registered with us. You are not obliged to register with us, but if you do not do so, you will be unable to download the Apps from the website or may be unable to use the relevant features, functions or content of the Apps downloaded from any third party application store (as the case may be). You must ensure that any registration details you provide are accurate.</p>

              <p>To access the Service, you must enter your mobile telephone number, email address or social media network login details when prompted on first launching the Apps and follow the subsequent instructions to complete the account registration process. We may, during the registration process and from time to time, offer you the ability to link your user account to certain social media networks to enable you to (i) invite friends through your social media networks to use the Service; and (ii) to allow you to publish notifications to such networks with a link to the Service or a Pearl or Guide. Please refer to our Privacy Policy for further details.</p>

              <p>We reserve the right to disable any user account, at any time, if in our opinion you have failed to comply with any of the provisions of these terms or if any details you provide for the purposes of registering as a user proves to be false.</p>

              <p>We reserve the right to withdraw or suspend the operation of our Apps, or cease to provide and/or update content to our Apps, with or without notice to you, if we need to do so, including, without limitation, for security, legal or business reasons.</p>

              <h3 id="whatyouareallowedtodo">What you are allowed to do</h3>

              <p>You may only use the Apps for your non-commercial, personal use and only in accordance with these terms, for lawful purposes (complying with all applicable laws and regulations), and in a responsible manner.</p>

              <p>Subject to the following sections, you may retrieve and display content from the Apps on a computer or mobile device and store the Apps in electronic form incidentally in the normal course of use of your browser or mobile device. Additional terms may also apply to certain features, parts or content of the Apps and, where such terms apply, will be displayed before you access the relevant features, parts or content.</p>

              <h3 id="whatyouarenotallowedtodo">What you are not allowed to do</h3>

              <p>Except to the extent expressly set out in these terms, you are not allowed to:</p>

              <ul>
                <li>republish, redistribute or re-transmit any part of the Apps or website;</li>

                <li>copy or store the Apps or any content from the website other than for your own non-commercial, personal use and as may occur incidentally in the normal course of use of your browser or mobile device;</li>

                <li>store the Apps on a server or other storage device connected to a network or create a database by systematically downloading and storing any data from the Apps;</li>

                <li>remove or change any content of the Apps, website or Services, or attempt to circumvent security or interfere with the proper working of the Apps, website or Services, or any servers on which they are hosted;</li>

                <li>use the Apps, website or Services in any way that might damage our name or reputation or that of any of our affiliates; or</li>

                <li>otherwise do anything that it is not expressly permitted by these terms.</li>
              </ul>

              <p>In order to do anything with the Apps, website or Services which is not expressly permitted by these terms, you will need a separate licence from us. Please contact us, using the <a href="#contacting-us">contacting us</a> details at the end of these terms.</p>

              <h3 id="userguidelines">User guidelines</h3>

              <p>We want you to enjoy using our website, Apps and Services, but please do so responsibly and with regard to others (including us, and other users). Please follow the rules set out below.</p>

              <ul>
                <li>Register when you first start using the Services. Make sure that all of the details that you give us are accurate.</li>

                <li>Make sure that any content (whether Pearls, Guides or otherwise) that you upload is your own. If you want to upload a photograph, it should be one that you have taken yourself.  If you are uploading comments or other text to Pearls or Guides, please use your own words and not someone elses.</li>

                <li>Only upload content if you are happy for us to use it (because, if you submit content, we would like to use it in accordance with the <a href="#intellectual-property-rights-and-use-of-content">licence</a> set out below).</li>

                <li>Behave in an appropriate way. Our users have a wide variety of opinions and beliefs, so please be polite and avoid uploading or doing anything that might reasonably be expected to give offence to other users.</li>

                <li>Comply with any reasonable requests from us with regard to the use of the <a href="/">website</a>, Apps and/or Services.</li>

                <li>If you notice anything when using the website or Apps that you think is unlawful or inappropriate, let us know via our website.</li>

                <li>Do not upload any content that is unlawful.  This includes anything that is obscene, pornographic, defamatory or otherwise prohibited.</li>

                <li>Do not be rude or unpleasant.  Do not use the Services to abuse, harass or otherwise behave inappropriately to us or any other user.</li>

                <li>Do not impersonate anyone else.</li>
              </ul>

              <h3 id="thirdpartyserviceprovidersandapplicationstores">Third party service providers and application stores</h3>

              <p>Certain third party service providers with whose devices and/or operating systems our Apps have been designed to be compatible with require us to include some additional provisions in these terms. These are set out at the end of these terms under <a href="#additional-terms-from-third-party-service-providers">Additional third party terms</a>.</p>

              <h3 id="useofthewebsiteandorapps">Use of the website and/or Apps</h3>

              <p>We do not guarantee the continuous, uninterrupted or error-free operation of the website or Apps, or that the website or Apps will perform at a certain speed (since this depends on a number of factors outside our control such as failures of internet access) and, in particular, the website and/or Apps may be unavailable from time to time due to scheduled maintenance or upgrades.</p>

              <p>We may withdraw or suspend the operation of the website, Apps or Services, or cease to provide and/or update content to the website, with or without notice to you, if we have reasonable grounds for doing so, including for security, legal or business reasons.</p>

              <p>We may impose limits on certain features of the website or restrict your access to parts or all of it without notice or liability.</p>

              <p>You should use the website and Apps in a lawful manner and, in particular, you should not use the website or Apps (or upload anything to the website, Apps or the Services) in such a way as to:</p>

              <ul>
                <li>upload, store or transmit any malicious code or other similar harmful software;</li>

                <li>remove or change any content of the website or Apps, or attempt to circumvent security or interfere with the proper working of the website, Apps or any servers on which the website and Apps are hosted;</li>

                <li>use the website or Apps in a way that might damage our name or reputation or that of any of our affiliates; or</li>

                <li>otherwise do anything that is not expressly permitted by these terms.</li>
              </ul>

              <p>You may not (directly or indirectly):</p>

              <ul>
                <li>copy any part of the website or Apps (except to the extent that this occurs automatically in the normal course of your accessing the website using a browser); or</li>

                <li>modify, translate or otherwise create derivative works from any part of the website or Apps.</li>
              </ul>

              <p>We do not guarantee that any particular content will be made available via the website or Apps. We do not (and have no obligation to) monitor the use of the website, Apps or any content uploaded to it by users. We will not be liable for any errors or omissions in any content provided by users (for example, any inaccurate or incomplete user postings).</p>

              <h3 id="intellectualpropertyrightsanduseofcontent">Intellectual property rights and use of content</h3>

              <p>All intellectual property rights in the website, Apps and in any content of the website or Apps (including text, graphics, software, photographs and other images, videos, sound, trade marks and logos) are owned by us or by our licensors (who may be other users). Except as expressly set out in the terms, nothing in these terms gives you any rights in respect of any intellectual property owned by us or our licensors and you acknowledge that you do not acquire any ownership rights by using the website, Apps or any content therein.</p>

              <p>In relation to any content that you submit so as to be accessible via the website or Apps:</p>

              <ul>
                <li>subject to the terms set out below, any intellectual property rights that you own in such content will be retained by you; and</li>

                <li>you waive any moral rights you may have in, or to be identified as the author of, such content.</li>
              </ul>

              <p>In relation to any content (including photos) that you submit to or via the website or Apps, you grant us a worldwide, royalty-free and non-exclusive licence to copy, adapt and publish the content:</p>

              <ul>
                <li>via the Services;</li>

                <li>if you were referred or linked to the Services from another website or application, via that other website or application;</li>

                <li>if the Services are linked to any other website or application, via that other website or application;</li>

                <li>in other versions of the website or App that we operate, either on our own behalf or on behalf of third parties;</li>
              </ul>

              <p>provided that this licence will continue to apply while you continue to include the relevant content on the Services and shall come to an end when you delete that content from the Services. You further agree to waive any moral rights you may have in, or to be identified as the author of, such content.</p>

              <p>You are responsible for ensuring that, in relation to any Pearls, Guides or other content submitted by you, you own the intellectual property rights in such Pearls, Guides or the content concerned or you otherwise have the right to submit the Pearls, Guides or content and grant the licences set out above in relation to those Pearls, Guides or content.</p>

              <p>If you do not want any content submitted by you to be subject to these licence terms, then you should not submit it.</p>

              <h3 id="functionalityandcontent">Functionality and content</h3>

              <p>We may change the design, features and/or functionality of the website or Apps from time to time. The content of the website or Apps may be updated at any time.</p>

              <p>Whilst we try to make sure that content made available on the website or Apps consisting of information of which we are the source is correct, the website or Apps may make content available which is derived from a number of sources (including users), for which we are not responsible. In all cases, information made available by the website or Apps is not intended to amount to authority or advice on which reliance should be placed.</p>

              <p>We do not pre-screen content uploaded by users, but we reserve the right, in our sole discretion, to delete, edit or modify any content submitted by you or any other user, at any time and without notice to you.</p>

              <p>Complaints about any content should be sent to us via our <a href="/">website</a> and should contain details of the specific content giving rise to the complaint.</p>

              <p>Except as expressly set out in these terms, we do not give or enter into any representation, condition, warranty or other terms as to the accuracy, completeness, currency, correctness, reliability, integrity, quality, fitness for purpose or originality of any content of the website or Apps and, to the fullest extent permitted by law, all implied conditions, warranties or other terms of any kind are hereby excluded. To the fullest extent permitted by law, we accept no liability for any loss or damage of any kind incurred as a result of you or anyone else that arises from the use of the website, Apps or of any content included on the website or Apps.</p>

              <p>We cannot and do not guarantee that the website, Apps and its content will be free from viruses and/or other code that may have contaminating or destructive elements. It is your responsibility to implement appropriate security safeguards (including anti-virus and other security checks) to satisfy your particular requirements as to the safety and reliability of the website, Apps and its content.</p>

              <h3 id="yourpersonalinformation">Your personal information</h3>

              <p>Use of your personal information submitted to us (whether via the Apps or the website) is governed by our <a href="#privacy-policy">Privacy Policy</a>.</p>

              <h3 id="externallinks">External links</h3>

              <p>The Apps and/or website may, from time to time, include links to external sites, which may include links to third party offers and promotions. We include these to provide you with access to information, products or services that you may find useful or interesting. We are not responsible for the content of these sites or for anything provided by them and do not guarantee that they will be continuously available. The fact that we include links to such external sites does not imply any endorsement of, or association with, their operators or promoters.</p>

              <h3 id="ourliability">Our liability</h3>

              <p>Nothing in these terms shall limit or exclude our liability to you for:</p>

              <ul>
                <li>death or personal injury caused by our negligence;</li>

                <li>fraudulent misrepresentation; or</li>

                <li>any other liability that may not, under English law, be limited or excluded.</li>
              </ul>

              <p>Subject to this, if you are a consumer and not a business user, in no event shall we be liable to you for any business losses, and if you are a business user, in no event shall we be liable to you for any indirect or consequential losses, or for any loss of profit, revenue, contracts, data, goodwill or other similar losses, and any liability we do have for losses you suffer is strictly limited to losses that were reasonably foreseeable and shall not, in aggregate, exceed the sum of £100.</p>

              <p>We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations that is caused by events outside our reasonable control.</p>

              <h3 id="general">General</h3>

              <p>You may not transfer or assign any or all of your rights or obligations under these terms.</p>

              <p>All notices given by you to us must be given in writing to the email address set out at the end of these terms and conditions.</p>

              <p>If we fail to enforce any of our rights, that does not result in a waiver of that right.</p>

              <p>If any provision of these terms and conditions is found to be unenforceable, all other provisions shall remain unaffected.</p>

              <p>These terms may not be varied except with our express written consent.</p>

              <p>These terms and any document expressly referred to in them represent the entire agreement between you and us in relation to their subject matter. We are required by law to advise you that any contract formed on these terms may be concluded in the English language only and that no public filing requirements apply.</p>

              <p>These terms shall be governed by English law, and you agree that any dispute between you and us regarding them, the Apps or the website will only be dealt with by the English courts, provided that, if you live in a part of the United Kingdom other than England, the applicable law of that part of the United Kingdom will govern and any dispute will only be dealt with by the courts there. Nothing shall prevent us from bringing proceedings to protect our intellectual property rights before any competent court.</p>

              <h3 id="contactingus">Contacting us</h3>

              <p>Please submit any questions you have about these terms or any problems concerning the Apps, website or Service to us by the following means:</p>

              <ul>
                <li>via the website; or</li>

                <li>by email to: contact@socialbank.co.</li>
              </ul>

              <hr />

              <h2 id="privacypolicy">Privacy Policy</h2>

              <h3 id="introduction-1">Introduction</h3>

              <p>This is the privacy and cookies policy for <a href="www.socialbank.co">www.socialbank.co</a>.</p>

              <p>We are committed to protecting your privacy online. We appreciate that you do not want the personal information you provide to us to be distributed indiscriminately and here we explain how we collect information, what we do with it and what controls you have over it.</p>

              <p>By using the Site, Apps or other services as operated and made available by us from time to time ("<strong>Services</strong>"), you consent to the collection and use of information in accordance with this privacy policy.</p>

              <p>We reserve the right to change this privacy policy from time to time by changing it on the Site or updating the Apps. This privacy policy was last updated on 2nd June 2017.</p>

              <h3 id="informationwemaycollectfromyou">Information we may collect from you</h3>

              <p>We may collect and process the following personal information about you:</p>

              <ul>
                <li>information (such as your name, telephone number, email address, social media account details, social media connections, phonebook contacts and photographs) that you provide by completing forms on the Site or Apps, including if you register as a user of the Site or Apps (whether through certain social media channels or otherwise), upload or submit any materials via the Site or Apps, or request any information from us;</li>

                <li>in connection with an account sign-in facility, your log-in and password details;</li>

                <li>communications you send to us, for example to report a problem or to submit queries, concerns or comments regarding the Site, Apps or its content;</li>

                <li>information from surveys, promotions and competitions that we may, from time to time, run on the Services, if you choose to respond to, or participate in, them;</li>

                <li>technical information from your mobile device (such as location data and contacts from your phonebook) relating to the service you receive;</li>

                <li>information relating to your real-time location;</li>

                <li>information that you post in the form of comments or contributions to the Service via the Site or Apps, which may include search terms you enter into the Site or Apps.</li>
              </ul>

              <p>You are under no obligation to provide any such information. However, if you should choose to withhold requested information, we may not be able to provide you with certain services.</p>

              <h3 id="usesofyourinformation">Uses of your information</h3>

              <p>We will use the personal information you provide to:</p>

              <ul>
                <li>identify you when you sign-in to your account;</li>

                <li>enable us to provide you with the services and information offered through the Site or Apps which you request. This may include:

                  <ol>
                    <li>disclosing and sharing your information to certain third parties if you were referred or linked to our Site or Apps from another third party website or application, or if our services are linked to another website or application which you access via our service;</li>

                    <li>sending push notifications to contacts within your phonebook, social media networks or directly (for example by email) who are not existing users of the Service, if: (i) you have elected to share a Pearl or Guide (as defined in our <a href="#terms-of-service">Terms of Service</a>) with a friend or member of the wider public by sending a URL web link (generated by us) which can be copied into a messaging service of your choice; or (ii) you invite your friends to join the Service;</li>

                    <li>accessing your social media profiles, friends or connections, and email addresses if you choose to link your account to any social media networks made available through the Service;</li>
                  </ol>
                </li>

                <li>administer your account with us;</li>

                <li>analyse use of the Apps and the people using the Apps in order to improve our content and services including research into our user demographics;</li>

                <li>we collect your real time location to provide location services requested by you in order to allow use of tagging features on the service (whether via the Site or Apps) by you. You may opt out at any time from allowing further access by us to your location data by going to your device settings and turning off location services. You can also stop all information collection by uninstalling the Apps. You may use the standard uninstall processes as may be available as part of your mobile device or via the Apps market place network;</li>

                <li>send you information we think you may find useful or which you have requested from us, including receipt of marketing communications such as exclusive offers and loyalty rewards, provided you have indicated that you are happy to be contacted for these purposes by post, email, mobile messaging, telephone communications and/or through any other electronic or digital means including social network platforms.</li>
              </ul>

              <p>You can tell us not to contact you with information regarding our products and services either at the point such information is collected on the Apps (by checking or unchecking (as directed) the relevant box) or, where you do not wish us to continue to use your information in this way, by following the unsubscribe instructions on any communications sent to you. You can also exercise this right at any time by contacting us using the <a href="#contacting-us">contacting us</a> details at the end of this privacy policy.</p>

              <h3 id="privacysettings">Privacy settings</h3>

              <p>All factual information (such as phone numbers, addresses, website URLs, photos and other similar information) relating to Pearls or Guides which you upload to the Service will be publically available to other users of the Service. You can choose to make other elements of each Pearl or Guide (such as comments and private notes) available to you only or publically available to other users by setting your privacy settings for each Pearl or Guide before each Pearl or Guide is posted to the Service.</p>

              <p>When you share information via the Site or Apps, you should think carefully about who you wish to share that information with and adjust your privacy settings accordingly.</p>

              <p>Your name, user name and any other information you choose to share on your user profile will be publically available to other users and searchable within the Service directory and accessible to other users.</p>

              <p>If you choose to share Pearls or Guides with friends or other members of the public who are not users of the Service, only public content will be available for viewing by those people. If you choose to share or forward a Pearl or Guide with a friend who is an existing user of the Service (irrespective of whether the Pearl or Guide you are sharing is your own Pearl or Guide or that of another user with whom you are connected), only public content will be available for viewing by those friends you choose to share the Pearl or Guide with.</p>

              <h3 id="additionalinformation">Additional information</h3>

              <p>When you access or use the Site or Apps, we may automatically collect additional information about you, such as the type of internet browser or mobile device you use, any website from which you have come to the Apps and your IP address (the unique address which identifies your device on the internet) and your operating system, which are automatically recognised by our web server. You cannot be identified from this information and it is only used to assist us in providing an effective service on the relevant Apps and to collect broad demographic information for aggregate use.</p>

              <h3 id="cookieandsimilartechnology">Cookie and similar technology</h3>

              <p>The Site and Apps uses cookies or similar technology to collect information about your access to the Site or access and use of the Apps.</p>

              <p>Cookies are pieces of information that include a unique reference code that a website transfers to your device to store and sometimes track information about you. A number of cookies we use only last for the duration of your web session and expire when you close your browser. Other cookies are used to remember you when you return to the Site or Apps and will last for longer.</p>

              <p>We use cookies to:</p>

              <ul>
                <li>remember that you have used the Site or Apps before – this means that we can identify the number of unique visitors we receive and allows us to make sure that we have enough capacity for the number of users we get;</li>

                <li>allow you to navigate the Site and Apps more easily;</li>

                <li>remember your login session so you can move from one page to another within the Site or Apps;</li>

                <li>store your preferences;</li>

                <li>customise elements of the layout and/or content of the pages of the Site or Apps for you;</li>

                <li>audit the downloading of data from the Site.</li>
              </ul>

              <p>Some of the cookies used on our Site or Apps are set by us and some are set by third parties who are delivering services on our behalf.</p>

              <p>Most computer and some mobile web browsers automatically accept cookies but, if you prefer, you can change your browser to prevent that or to notify you each time a cookie is set. You can also learn more about cookies by visiting <a href="http://www.allaboutcookies.org">www.allaboutcookies.org</a> which includes additional useful information on cookies and how to block cookies using different types of browser. Please note however, that by blocking or deleting cookies you may not be able to take full advantage of the Site or Apps (as the case may be).</p>

              <h3 id="informationsharing">Information sharing</h3>

              <p>We may disclose aggregate statistics about visitors to, and users of, the Site and the Apps in order to describe our services to prospective partners, advertisers, sponsors and other reputable third parties and for other lawful purposes, but these statistics will include no personally identifiable information.</p>

              <p>We may disclose your personal information to any of our affiliates, or to our agents or contractors who assist us in providing the services we offer through the Site or Apps, processing transactions, fulfilling requests for information, receiving and sending communications, updating marketing lists, analysing data, providing support services or in other tasks from time to time. Our agents and contractors will only use your information to the extent necessary to perform their functions.</p>

              <p>In the event that we undergo re-organisation or are sold to a third party, you agree that any personal information we hold about you may be transferred to that re-organised entity or third party.</p>

              <p>We may disclose your personal information if required to do so by law or if we believe that such action is necessary to prevent fraud or cybercrime or to protect the Site, Apps or the rights, property or personal safety of any person.</p>

              <h3 id="publicforums">Public forums</h3>

              <p>The Site and/or Apps may, from time to time, make comment facilities, message boards and/or other public forums available to its users. Any information that is disclosed in these areas becomes public information and you should exercise caution when using these and never disclose your personal information.</p>

              <h3 id="childsafety">Child safety</h3>

              <p>Our Services are designed for use by those aged 13 years or over. If you are less than 13 years old, we are afraid that you cannot use the Services. If you are 13 years old or older, but under the age of 18, please go through these terms with your parent or guardian and make sure that both of you are happy with them and agree with them before signing up to use the Services.</p>

              <h3 id="externallinks-1">External links</h3>

              <p>The Site and Apps may, from time to time, contain links to external sites. We are not responsible for the privacy policies or the content of such sites.</p>

              <h3 id="security">Security</h3>

              <p>We place great importance on the security of all personally identifiable information associated with our users. We have security measures in place to attempt to protect against the loss, misuse and alteration of personal information under our control. For example, our security and privacy policies are periodically reviewed and enhanced as necessary and only authorised personnel have access to personal information. Whilst we cannot ensure or guarantee that loss, misuse or alteration of information will never occur, we use all reasonable efforts to prevent it.</p>

              <h3 id="datastorageandinternationaltransfers">Data storage and international transfers</h3>

              <p>Information that you submit via the Site or Apps is sent to and stored on secure servers located in the European Economic Area (“<strong>EEA</strong>”). If you make contact with any business featured on the Site your details may be transferred outside the EEA. If we transfer your information outside the EEA in this way, we will take steps to ensure that your privacy rights continue to be protected. By submitting information via the Site or Apps, you agree to this storing, processing and/or transfer.</p>

              <p>If you use our services while you are outside the EEA, your information may be transferred outside the EEA in order to provide you with those services.</p>

              <h3 id="yourrights">Your rights</h3>

              <p>You have a legal right under the Data Protection Act 1998 to a copy of all the personal information about you held by us. On request, we will provide you with a copy of this information subject to a fee not exceeding the prescribed fee permitted by law. You also have a right to correct any errors in that information. As mentioned above, you have a right to prevent the use of your personal information for direct marketing purposes.</p>

              <h3 id="contactingus-1">Contacting us</h3>

              <p>Please submit any questions, concerns or comments you have about this privacy policy or any requests concerning your personal data by any of the following means:</p>

              <ul>
                <li>via the website;</li>
                <li>by email to: <a href="contact@socialbank.co">contact@socialbank.co</a></li>
              </ul>
            </div>
          </div>
          <Footer />
        </main>
      </div>
    )
  }
}

export default About
